In [57]:
import cv2
from ultralytics import YOLO
import cvzone
import math

from sort import *

In [58]:
# creating web cam object
# cap = cv2.VideoCapture(0)
cap = cv2.VideoCapture('./Videos/cars.mp4')
#cap.set(3,1280) # for width
#cap.set(4,720) #for height

In [59]:
model = YOLO('./Yolo-Weights/yolov8n.pt')

In [60]:
# classes that will be detected and displayed
classNames = ["person", "bicycle", "car", "motorbike", "aeroplane", "bus", "train", "truck", "boat",
              "traffic light", "fire hydrant", "stop sign", "parking meter", "bench", "bird", "cat",
              "dog", "horse", "sheep", "cow", "elephant", "bear", "zebra", "giraffe", "backpack", "umbrella",
              "handbag", "tie", "suitcase", "frisbee", "skis", "snowboard", "sports ball", "kite", "baseball bat",
              "baseball glove", "skateboard", "surfboard", "tennis racket", "bottle", "wine glass", "cup",
              "fork", "knife", "spoon", "bowl", "banana", "apple", "sandwich", "orange", "broccoli",
              "carrot", "hot dog", "pizza", "donut", "cake", "chair", "sofa", "pottedplant", "bed",
              "diningtable", "toilet", "tvmonitor", "laptop", "mouse", "remote", "keyboard", "cell phone",
              "microwave", "oven", "toaster", "sink", "refrigerator", "book", "clock", "vase", "scissors",
              "teddy bear", "hair drier", "toothbrush" , "pen"
              ]

In [61]:
mask = cv2.imread('./mask.png')

In [62]:
# creating a instance for tracking
tracker = Sort(max_age=20,min_hits=3,iou_threshold=0.3)

# we will make a line and count after that 
limits = [423,297,673,297]

In [63]:
while True:
    success, img = cap.read()
    #overlay mask on the image/webcam feed
    imageRegion = cv2.bitwise_and(img,mask)
    # results = model(img,stream=True)
    results = model(imageRegion,stream=True)
    
    detections = np.empty((0,5))
    
    for r in results:
        boxes = r.boxes
        for box in boxes:
            # xy1 are points and xy2 are height and width
            x1,y1,x2,y2 = box.xyxy[0]
            # converting them into integers instead for tensor 
            x1,y1,x2,y2 = int(x1),int(y1),int(x2),int(y2)
            # cv2.rectangle(img,(x1,y1),(x2,y2),(255,0,255),3) #using cv2 reactangle
            w,h = x2-x1 , y2-y1
            bbox = int(x1),int(y1),int(w),int(h)
            
            # print(x1,y1,x2,y2)
            
            # cvzone.cornerRect(img,(x1,y1,w,h),l=9) #using cvzone rectange
            
            #confidence
            conf = math.ceil((box.conf[0]*100))/100 #for confidence values
            print(conf)
            #classnames
            cls = int(box.cls[0])
            #to display conf and object class on webcam
            currentclass = classNames[cls]
            
            if currentclass == "car" or currentclass == "truck" or currentclass == "bus" or currentclass == "motorbike" and conf>0.3 :
                # cvzone.putTextRect(img,f'{currentclass} {conf}',(max(0,x1),max(35,y1)) , scale=0.6,thickness=1,offset=3)
                cvzone.cornerRect(img,(x1,y1,w,h),l=9 , rt=5) #using cvzone rectange
                currentArrays = np.array([x1,y1,x2,y2,conf])
                detections = np.vstack((detections,currentArrays))
            
    resultsTracker = tracker.update(detections)
    
    cv2.line(img,(limits[0],limits[1]),(limits[2],limits[3]),(0,0,255),5)
    
    for result in resultsTracker:
        x1,y1,x2,y2,id = result
        # converting them into integers instead for tensor 
        x1,y1,x2,y2 = int(x1),int(y1),int(x2),int(y2)
        print(result)
        w,h = x2-x1 , y2-y1
        cvzone.cornerRect(img,(x1,y1,w,h),l=9 , rt=2,colorR=(255,0,0))
        cvzone.putTextRect(img,f' {int(id)}',(max(0,x1),max(35,y1)) , scale=2,thickness=3,offset=10)
    
    cv2.imshow("Image",img)
    # cv2.imshow("ImageRegion",imageRegion)
    # cv2.waitKey(1)
    # Wait for a key event, but only for a short duration (10 milliseconds)
    # If the key is Esc (27), then break out of the loop and close the webcam
    if cv2.waitKey(0) == 27:
        break

# Release the webcam and close all OpenCV windows
cap.release()
cv2.destroyAllWindows()

0.82
0.79
0.49
0.39


0: 384x640 4 cars, 146.2ms
Speed: 17.8ms preprocess, 146.2ms inference, 16.3ms postprocess per image at shape (1, 3, 384, 640)


[        572         322         651         429         245]
[        573         364         626         429         244]
[        378         348         497         457         243]
[        456         225         510         270         242]



0: 384x640 4 cars, 85.1ms
Speed: 3.3ms preprocess, 85.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)


0.8
0.77
0.53
0.52
[     568.48      320.73      651.52      436.27         245]
[     572.26      371.69      627.74      438.31         244]
[     373.12      349.89      492.88      459.11         243]
[     454.74      228.22      508.26      273.78         242]



0: 384x640 2 cars, 77.4ms
Speed: 2.0ms preprocess, 77.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)


0.84
0.8
[     355.68      365.44      476.85      468.27         243]
[     447.68      233.63      501.97      279.13         242]



0: 384x640 3 cars, 80.7ms
Speed: 3.0ms preprocess, 80.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)


0.53
0.53
0.38
[     340.18      389.65      456.14      471.21         243]
[     437.23      243.33      494.88       291.5         242]



0: 384x640 2 cars, 77.8ms
Speed: 2.1ms preprocess, 77.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)


0.62
0.33
[     329.19      415.66      431.62      473.23         243]
[     425.72       251.9      488.28      303.79         242]



0: 384x640 2 cars, 76.8ms
Speed: 3.1ms preprocess, 76.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)



0.81
0.64
[     414.95      260.16      478.66      313.73         242]


0: 384x640 3 cars, 73.7ms
Speed: 2.0ms preprocess, 73.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)


0.85
0.66
0.38
[     403.36       268.9      470.65       325.2         242]



0: 384x640 3 cars, 78.2ms
Speed: 3.1ms preprocess, 78.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)


0.81
0.78
0.4
[     391.16      277.99      461.47      336.97         242]



0: 384x640 3 cars, 79.8ms
Speed: 1.4ms preprocess, 79.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)


0.87
0.83
0.65
[     604.53      221.37      660.48      279.16         246]
[      375.2      287.28      450.66      351.49         242]



0: 384x640 3 cars, 82.9ms
Speed: 2.0ms preprocess, 82.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)


0.9
0.82
0.68
[     494.81      198.91      541.78      227.66         247]
[     600.32      231.93      660.04      293.02         246]
[     359.19      299.31       439.4      367.66         242]



0: 384x640 4 cars, 101.5ms
Speed: 3.0ms preprocess, 101.5ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)



0.87
0.85
0.68
0.32
[     489.11      199.67      538.32      232.06         247]
[     592.72      243.59      655.27      308.58         246]
[     340.76      311.86      427.07      385.53         242]


0: 384x640 3 cars, 68.7ms
Speed: 2.0ms preprocess, 68.7ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)



0.85
0.63
0.56
[     484.86      203.33      535.69      238.66         247]
[     585.29      254.56      653.08      325.61         246]
[     320.84      325.91      412.35      403.99         242]


0: 384x640 4 cars, 77.1ms
Speed: 2.0ms preprocess, 77.1ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)



0.87
0.82
0.71
0.45
[     480.47      205.39      531.74      243.35         247]
[     578.04      268.94      652.39      346.41         246]
[     296.59      342.28      394.62      425.48         242]
0.86
0.77
0.75
0.6


0: 384x640 4 cars, 73.0ms
Speed: 2.5ms preprocess, 73.0ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 cars, 74.4ms
Speed: 1.1ms preprocess, 74.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)


[     475.45      209.69      527.24      249.49         247]
[     570.86       284.7      654.98      370.28         246]
[     270.79      358.68      375.77      448.23         242]
0.76
0.75
0.71
0.54
[     569.45      205.93      608.21      237.79         248]
[     468.96      216.06      521.76      256.86         247]
[     556.32      302.74      643.06      394.69         246]
[     237.52       376.3      352.94       467.5         242]



0: 384x640 6 cars, 78.7ms
Speed: 2.0ms preprocess, 78.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)


0.81
0.77
0.57
0.48
0.33
0.27
[     566.59      213.18      604.94      245.77         248]
[     462.11      222.16      516.46      264.96         247]
[     541.03      324.57      632.09      424.97         246]
[     199.79       392.6      327.73      477.97         242]



0: 384x640 5 cars, 77.1ms
Speed: 3.2ms preprocess, 77.1ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)



0.76
0.75
0.72
0.68
0.36
[     560.37      220.51      600.68       255.4         248]
[     453.93      228.74      508.43      272.69         247]
[     526.23      347.52       623.5      456.22         246]
0.81
0.73
0.7
0.64


0: 384x640 4 cars, 68.5ms
Speed: 3.6ms preprocess, 68.5ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)


[     554.43      227.52      596.94      265.75         248]
[     445.59      234.36      503.11      281.37         247]
[     510.66      370.03      612.19      473.24         246]



0: 384x640 5 cars, 1 truck, 74.8ms
Speed: 2.0ms preprocess, 74.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)


0.88
0.76
0.72
0.59
0.47
0.29
[     616.58      206.36      659.81       278.2         250]
[     548.11      234.61       593.2      275.37         248]
[     435.36      241.14      495.33      290.19         247]
[     495.38      396.39      600.68      482.21         246]



0: 384x640 1 person, 5 cars, 92.1ms
Speed: 2.0ms preprocess, 92.1ms inference, 0.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 cars, 70.0ms
Speed: 2.5ms preprocess, 70.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)


0.87
0.85
0.69
0.47
0.45
0.33
[     612.81      221.12      660.92       294.3         250]
[     540.47      242.77      588.66      287.05         248]
[     424.74      248.97      487.68       300.4         247]
0.85
0.83
0.67
0.66
[     606.76      230.36       660.4      310.78         250]
[     532.97      252.22      583.91      299.85         248]
[     411.73      258.64      477.74      312.96         247]



0: 384x640 4 cars, 99.4ms
Speed: 3.0ms preprocess, 99.4ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 person, 4 cars, 71.8ms


0.86
0.86
0.73
0.73
[     545.29      201.49      594.04       233.8         252]
[     598.61      241.14      657.95         329         250]
[     524.13      262.52       578.5      313.29         248]
[     396.97      268.35      466.52      325.03         247]
0.8
0.74
0.65
0.52
0.29


Speed: 2.2ms preprocess, 71.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 person, 4 cars, 73.3ms


[     541.45      206.36      590.84      240.14         252]
[     591.61      253.86      657.97      350.48         250]
[     514.42      273.06      572.59      327.66         248]
[     379.68      281.12       454.1      341.72         247]
0.88
0.84
0.83
0.61
0.34


Speed: 1.4ms preprocess, 73.3ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 cars, 69.1ms
Speed: 2.1ms preprocess, 69.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)


[     535.79         209      587.96      248.04         252]
[     581.64      270.52       656.1      376.57         250]
[     503.23      286.86       565.7      345.78         248]
[     360.42      294.23      440.98      358.95         247]
0.85
0.83
0.82
0.44
0.31
[     531.63      213.02      584.59         255         252]
[     571.06      289.41      653.13      406.06         250]
[     490.71      302.15      557.93       366.3         248]
[     338.28      308.86      425.22      378.87         247]



0: 384x640 5 cars, 74.4ms
Speed: 2.3ms preprocess, 74.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)



0.86
0.82
0.75
0.47
0.27
[     526.61      219.11      581.04      264.21         252]
[     555.27      313.97      642.69      442.52         250]
[     476.89      318.34      548.69      387.95         248]
[     311.87      326.94       407.1      402.12         247]
0.83
0.82
0.72
0.58


0: 384x640 4 cars, 83.6ms
Speed: 3.0ms preprocess, 83.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 cars, 73.8ms
Speed: 2.0ms preprocess, 73.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)


[     520.08      227.07      575.89      273.66         252]
[      538.8      334.25      632.38      465.67         250]
[     458.92      337.32         538      413.42         248]
[     281.08      347.26       385.7      428.89         247]
0.8
0.73
0.5
0.46
[     513.82      234.47      571.44      283.68         252]
[     439.82      359.87      525.06      442.99         248]
[     247.07      368.52      360.79      455.52         247]



0: 384x640 4 cars, 67.1ms
Speed: 2.4ms preprocess, 67.1ms inference, 2.3ms postprocess per image at shape (1, 3, 384, 640)



0.88
0.77
0.48
0.38
[      506.7      243.09      566.19      293.79         252]
[     418.06      381.22      510.31      464.08         248]
[      203.6      391.22      329.81      472.39         247]
0.84
0.52


0: 384x640 3 cars, 74.4ms
Speed: 2.4ms preprocess, 74.4ms inference, 0.5ms postprocess per image at shape (1, 3, 384, 640)



0.5
[     493.27      205.24      535.09      237.64         254]
[     497.78      252.34      560.17      306.36         252]
[     396.41      404.98      495.78      476.39         248]


0: 384x640 2 cars, 83.3ms
Speed: 2.0ms preprocess, 83.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)


0.86
0.75
[     487.24      210.07      530.31      244.65         254]
[     488.99      261.15      554.43      317.82         252]



0: 384x640 2 cars, 87.9ms
Speed: 2.0ms preprocess, 87.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)



0.9
0.8
[      479.5      214.97      524.83      251.89         254]
[     478.81       271.1      548.27      332.15         252]


0: 384x640 2 cars, 74.9ms
Speed: 2.2ms preprocess, 74.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)



0.87
0.8
[     471.22      222.01      517.76      260.56         254]
[     466.73      283.64      540.06      348.66         252]
0.9
0.78


0: 384x640 2 cars, 70.4ms
Speed: 2.0ms preprocess, 70.4ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)


[     462.39      230.16      511.27      269.97         254]
[      451.9      297.82      531.17      369.22         252]



0: 384x640 2 cars, 111.2ms
Speed: 4.6ms preprocess, 111.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)


0.9
0.86
[     452.11      237.56      504.24      280.02         254]
[     436.87      311.74       521.9      388.83         252]



0: 384x640 2 cars, 83.4ms
Speed: 1.0ms preprocess, 83.4ms inference, 0.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 cars, 76.4ms
Speed: 3.1ms preprocess, 76.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)


0.9
0.84
[      440.9      245.43      495.44      290.18         254]
[     419.02      329.63      510.02      413.13         252]
0.88
0.83



0: 384x640 3 cars, 74.8ms
Speed: 2.0ms preprocess, 74.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)


[     430.16      254.05      487.92      301.11         254]
[      398.3       350.6      497.05      442.15         252]
0.84
0.83
0.41
[     415.99      264.31      477.17      313.59         254]
[     375.16      368.57      481.12      461.96         252]



0: 384x640 3 cars, 79.5ms
Speed: 3.3ms preprocess, 79.5ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)


0.85
0.79
0.56
[     399.67      275.37      464.82       328.4         254]
[     352.74      388.74      464.47      474.22         252]



0: 384x640 3 cars, 97.4ms
Speed: 2.4ms preprocess, 97.4ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 cars, 71.8ms
Speed: 2.1ms preprocess, 71.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)


0.83
0.73
0.35
[     382.19       286.5      452.29      342.27         254]
[      330.7      406.11      444.89      480.02         252]
0.82
0.69
[     614.63      213.65      655.24      258.92         255]
[     361.79      301.34      437.62      360.64         254]



0: 384x640 3 cars, 78.9ms
Speed: 2.9ms preprocess, 78.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)


0.8
0.78
0.33
[     611.21      223.17      656.82      273.28         255]
[     339.65      316.37      420.88      379.88         254]



0: 384x640 2 cars, 80.9ms
Speed: 2.1ms preprocess, 80.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)



0.77
0.77
[     606.18      232.37      654.72      285.46         255]
[     313.72      333.46      402.64      402.64         254]


0: 384x640 3 cars, 77.9ms
Speed: 3.0ms preprocess, 77.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)


0.87
0.85
0.28
[     601.67      241.12      655.52      299.39         255]
[     283.29      354.83      379.73      429.74         254]



0: 384x640 3 cars, 77.7ms
Speed: 2.0ms preprocess, 77.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)


0.82
0.64
0.27
[      594.2      253.53      650.69      316.33         255]
[     249.65      376.96      354.72      456.61         254]



0: 384x640 3 cars, 79.4ms
Speed: 3.0ms preprocess, 79.4ms inference, 2.3ms postprocess per image at shape (1, 3, 384, 640)


0.79
0.62
0.26
[     504.86      199.96      541.54      225.99         256]
[     588.86      266.29      649.04      333.77         255]
[     203.45      399.86      321.36      473.66         254]



0: 384x640 2 cars, 89.8ms
Speed: 2.0ms preprocess, 89.8ms inference, 3.0ms postprocess per image at shape (1, 3, 384, 640)


0.72
0.65
[      502.1      200.12      540.13      228.37         256]
[     580.02      282.18      645.38      356.43         255]



0: 384x640 3 cars, 75.9ms
Speed: 2.5ms preprocess, 75.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)


0.68
0.66
0.3
[     499.94      200.68      538.94      230.62         256]
[     570.05      300.97      638.87      381.82         255]



0: 384x640 3 cars, 73.2ms
Speed: 3.0ms preprocess, 73.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)


0.77
0.56
0.55
[     497.62      202.03      537.46       234.3         256]
[     559.57      322.97      631.47      411.28         255]



0: 384x640 3 cars, 70.5ms
Speed: 3.3ms preprocess, 70.5ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)



0.7
0.6
0.58
[     496.08      202.65      536.44      237.37         256]
[     546.04      347.37      625.33      445.57         255]


0: 384x640 3 cars, 70.2ms
Speed: 2.4ms preprocess, 70.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)



0.42
0.4
0.35
[     617.17      215.28      657.72      263.98         257]
[     494.32      205.15      534.71       241.5         256]
[     534.14      371.47      616.29      468.11         255]
0.72
0.7


0: 384x640 2 cars, 73.7ms
Speed: 2.2ms preprocess, 73.7ms inference, 6.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 cars, 75.1ms
Speed: 1.4ms preprocess, 75.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)


[     615.48      225.38      659.18      274.16         257]
[      491.4      209.23      531.76      245.78         256]
0.77
0.7
[     611.06      232.89      659.15      285.45         257]
[     488.36      211.66      528.74      248.94         256]



0: 384x640 2 cars, 75.3ms
Speed: 3.3ms preprocess, 75.3ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 cars, 75.9ms
Speed: 2.0ms preprocess, 75.9ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)


0.84
0.59
[     606.84      240.38      659.81      297.69         257]
[     485.52      215.69      526.15      253.47         256]
0.73
0.72
0.38
0.34
[     601.38      249.53      657.14      309.97         257]
[     481.88       219.8      523.93      258.36         256]



0: 384x640 5 cars, 123.4ms
Speed: 2.5ms preprocess, 123.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 cars, 68.0ms
Speed: 2.6ms preprocess, 68.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)


0.82
0.77
0.57
0.55
0.47
[     593.56      261.51      652.55      325.44         257]
[     478.21      223.33      520.93      262.63         256]
0.83
0.79
0.74
0.5
0.33
[     587.31      274.12      651.06      343.05         257]
[     473.71      228.02      518.46      268.59         256]



0: 384x640 5 cars, 79.7ms
Speed: 2.6ms preprocess, 79.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)



0.84
0.82
0.77
0.74
0.41
[     562.87      202.38      609.62      239.81         259]
[     620.22      225.22      661.41      273.62         258]
[     579.05      287.69      649.27      363.32         257]
[     469.01      232.65      514.78      273.68         256]
0.85
0.77
0.75
0.73
0.45


0: 384x640 5 cars, 84.2ms
Speed: 3.7ms preprocess, 84.2ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 cars, 72.0ms
Speed: 2.0ms preprocess, 72.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)


[     557.65      206.61      606.72      247.91         259]
[     615.98      234.08      662.27      287.78         258]
[     569.63      304.16      642.47      385.27         257]
[     463.55       238.5      510.68      280.47         256]
0.85
0.75
0.74
0.63
0.61
[      502.9      200.29       542.9      223.14         261]
[     551.91      212.92      602.89      257.61         259]
[     610.97      238.17       663.4      299.62         258]
[     558.73      322.33      635.59      411.13         257]
[     457.03       243.3      505.89      287.43         256]



0: 384x640 6 cars, 77.8ms
Speed: 3.3ms preprocess, 77.8ms inference, 2.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 cars, 70.4ms
Speed: 2.2ms preprocess, 70.4ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)


0.88
0.76
0.7
0.65
0.63
0.42
[     501.94      200.74      543.87      226.32         261]
[     545.62      220.86      598.49      268.11         259]
[      607.9      244.82      663.89      310.27         258]
[        545      344.38      628.36      441.72         257]
[     451.24      247.69      502.36      293.13         256]
0.88
0.76
0.72
0.68
0.61
[      500.6      201.62      543.02      229.33         261]
[     539.89      228.51       593.9      278.23         259]
[     601.77      254.06      662.29      324.39         258]
[     529.41      365.03      618.56      464.93         257]
[     443.01      253.02      496.14      300.52         256]



0: 384x640 5 cars, 81.7ms
Speed: 1.4ms preprocess, 81.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 cars, 72.3ms
Speed: 2.9ms preprocess, 72.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)


0.84
0.81
0.78
0.72
0.54
[     499.31      205.22      541.46      233.28         261]
[     532.94      236.38       588.6      288.51         259]
[     595.64      263.54      661.68      338.27         258]
[     517.09      388.88      608.51      478.26         257]
[     434.37      259.13      489.71      308.13         256]
0.85
0.82
0.64
0.59
0.5
0.48
[     497.12      207.09      539.22      236.64         261]
[     523.31      245.38      582.62      301.14         259]
[     589.33      276.53      659.59      356.74         258]
[     425.16      265.66      483.65      316.98         256]



0: 384x640 5 cars, 75.9ms
Speed: 2.1ms preprocess, 75.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)



0.81
0.72
0.63
0.5
0.41
[     494.49      208.08      537.58      240.07         261]
[     512.83      254.87      574.97       314.5         259]
[     580.18      291.44      657.09      378.83         258]
[     414.93      273.22      475.93      326.71         256]
0.88
0.74
0.66
0.52
0.38
0.26


0: 384x640 6 cars, 73.6ms
Speed: 4.1ms preprocess, 73.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)



[     490.94      211.17      534.24       244.5         261]
[     501.25      266.73      567.54      330.54         259]
[      572.3      307.21      657.51      403.34         258]
[     401.92      280.78      466.09      335.85         256]
0.81
0.77


0: 384x640 6 cars, 77.6ms
Speed: 1.4ms preprocess, 77.6ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)



0.73
0.63
0.5
0.5
[     568.68      212.03      612.65      246.96         263]
[     487.33      214.81      531.38      249.47         261]
[     488.48       279.4      559.03      348.26         259]
[     557.45      329.17      643.86      431.42         258]
[      389.5       290.1      457.11      346.89         256]
0.75
0.72
0.65
0.56
0.54
0.44


0: 384x640 6 cars, 67.0ms
Speed: 2.0ms preprocess, 67.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 cars, 1 truck, 73.5ms
Speed: 3.1ms preprocess, 73.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)


[     565.03       217.6      610.46      255.81         263]
[     484.45      218.08      528.63      253.88         261]
[     473.02      294.66      549.76      369.55         259]
[      541.8       363.5      631.86      462.56         258]
[     374.74      300.28      446.47      360.41         256]
0.84
0.84
0.79
0.55
0.45
0.43
0.28
0.26
[      619.8      207.96      661.58      256.37         265]
[     560.01      224.68      606.65      265.29         263]
[     479.82      221.72      525.97      258.88         261]
[     453.75       311.2      537.12      393.11         259]
[     530.65      374.64      625.03      470.32         258]
[     358.23      310.84      434.14      374.78         256]



0: 384x640 6 cars, 1 truck, 74.2ms
Speed: 2.1ms preprocess, 74.2ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)



0.83
0.78
0.77
0.65
0.59
0.51
0.27
[     617.92       214.8      660.53      264.61         265]
[      553.4      232.91      602.08      275.62         263]
[     474.16      225.26      522.42      264.31         261]
[     432.53      331.49      523.14      421.41         259]
[     520.88      397.31       619.2      478.68         258]
[     340.66       321.7      420.96      389.27         256]
0.83
0.82
0.69
0.67
0.54


0: 384x640 5 cars, 72.3ms
Speed: 2.8ms preprocess, 72.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 cars, 70.3ms
Speed: 1.0ms preprocess, 70.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)


[     615.83       224.2      659.71      274.16         265]
[     547.59      240.81      598.07      286.16         263]
[     469.86      229.52      519.46       269.8         261]
[     402.63      355.62      503.51      452.92         259]
[     321.18      335.16      407.05      407.17         256]
0.9
0.83
0.82
0.73
0.67
[     611.66      232.65      659.54      285.74         265]
[     539.58      250.15      593.32      298.59         263]
[     464.37      234.78      515.13      275.89         261]
[      374.8      378.49      483.76      471.15         259]
[     298.35       349.8      390.98      427.44         256]



0: 384x640 5 cars, 76.9ms
Speed: 2.6ms preprocess, 76.9ms inference, 0.5ms postprocess per image at shape (1, 3, 384, 640)



0.85
0.83
0.77
0.74
0.58
[     606.82      239.14      658.87      296.06         265]
[     530.53      261.15      587.25       313.2         263]
[     457.45      239.47      509.98      281.81         261]
[     342.97      404.17      460.31      481.66         259]
[     273.89      365.74      372.53      449.01         256]
0.89
0.78
0.75
0.66
0.29


0: 384x640 5 cars, 71.9ms
Speed: 2.0ms preprocess, 71.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 cars, 70.4ms
Speed: 2.5ms preprocess, 70.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)


[     601.96      248.19      657.81      307.45         265]
[     521.03      273.88       580.8      328.74         263]
[     450.09      245.18      505.09      289.05         261]
[     246.28      381.18      351.22      464.16         256]
0.85
0.76
0.76
0.55
[     594.15      257.55      653.47      321.84         265]
[      509.4      287.15      573.55      346.66         263]
[     442.28      251.89      499.95      297.46         261]



0: 384x640 4 cars, 101.4ms
Speed: 2.0ms preprocess, 101.4ms inference, 7.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 cars, 73.6ms
Speed: 2.2ms preprocess, 73.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)


0.84
0.83
0.77
0.6
[     587.19      269.25       650.1      337.04         265]
[     495.58      302.04      565.46      365.95         263]
[     433.52      259.11      493.57      305.52         261]
0.86
0.81
0.81
0.66
[     564.19      208.33      605.33      235.75         267]
[     578.12       282.6      645.54      356.39         265]
[     479.43      320.35       555.3      389.49         263]
[     424.95      266.55      487.49      315.34         261]



0: 384x640 4 cars, 78.1ms
Speed: 2.7ms preprocess, 78.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)



0.86
0.74
0.72
0.52
[     560.42      209.69      604.05      240.34         267]
[     568.69       298.4      640.82      379.98         265]
[     413.99      275.19      480.09      326.66         261]
0.84
0.81
0.72
0.46
0.27


0: 384x640 5 cars, 72.8ms
Speed: 2.6ms preprocess, 72.8ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)



[     556.38      213.75      601.67      247.29         267]
[     558.15      316.19      635.07      405.99         265]
[     400.97      283.44      470.75      337.41         261]


0: 384x640 4 cars, 1 truck, 74.1ms
Speed: 1.1ms preprocess, 74.1ms inference, 2.1ms postprocess per image at shape (1, 3, 384, 640)



0.8
0.78
0.75
0.42
0.28
[     413.22      390.19      518.18       466.7         266]
[     545.88      336.99      628.31      437.14         265]
[     387.21      293.82      460.67      349.55         261]
0.77
0.77
0.67
0.37
0.36
0.35


0: 384x640 6 cars, 77.9ms
Speed: 2.0ms preprocess, 77.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 cars, 1 truck, 73.4ms


[     533.03      357.45      622.46      461.68         265]
[     370.67      304.91      448.93       364.9         261]
0.86
0.78
0.75
0.52
0.48
0.33


Speed: 3.6ms preprocess, 73.4ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 cars, 70.7ms
Speed: 2.0ms preprocess, 70.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)


[     518.02      200.34      560.22      231.16         268]
[     519.96      378.63      612.39      474.24         265]
[     353.16       317.2      436.51      381.15         261]
0.85
0.81
0.73
0.67
0.5
[     516.97      200.15       559.6      233.13         268]
[     534.31      241.16      584.57      280.62         267]
[     334.57      330.97      422.66      399.96         261]
[     630.27      246.93      665.55      291.68         260]



0: 384x640 4 cars, 74.5ms
Speed: 1.7ms preprocess, 74.5ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)



0.9
0.89
0.81
0.56
[     514.89      200.57      558.34      235.36         268]
[     526.46       249.7      579.71      292.44         267]
[      313.6      346.35      407.65      420.58         261]
[     625.86      256.87      664.47       302.5         260]
0.88
0.84
0.8
0.55
0.31


0: 384x640 5 cars, 70.5ms
Speed: 3.9ms preprocess, 70.5ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)



[     511.06      201.77      555.48      237.77         268]
[     517.72      258.33      573.38      303.55         267]
[      286.4      364.22      388.45      443.89         261]
[      620.9      268.43      662.74      316.31         260]


0: 384x640 6 cars, 109.9ms
Speed: 3.1ms preprocess, 109.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 cars, 73.6ms
Speed: 2.0ms preprocess, 73.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)


0.76
0.74
0.62
0.52
0.34
0.27
[        508      204.74      553.56      241.54         268]
[     507.54      269.06      565.65      316.29         267]
[     256.13      380.85      367.12      461.83         261]
[      615.3      282.03      660.57       332.4         260]
0.84
0.8
0.78
0.52
0.44
0.33
[     505.52      206.83      552.36      245.15         268]
[     496.81      280.82       558.1      331.34         267]
[     231.04      399.85      346.58      474.85         261]
[     607.82       296.7      658.59      350.95         260]



0: 384x640 5 cars, 91.5ms
Speed: 2.4ms preprocess, 91.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)



0.83
0.81
0.7
0.54
0.51
[     573.57      206.36      613.28      235.59         271]
[     503.07      207.37      550.93       247.9         268]
[     483.77      294.94      549.47      349.18         267]
[     600.38      313.23      657.91      372.82         260]
0.81
0.73
0.7
0.68
0.55


0: 384x640 5 cars, 75.0ms
Speed: 2.0ms preprocess, 75.0ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 cars, 67.2ms
Speed: 2.7ms preprocess, 67.2ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)


[      568.8      209.08       610.4      241.19         271]
[     499.51      209.21       548.5      252.49         268]
[     468.67      309.47      539.04      367.83         267]
[     589.94      333.41      651.61      398.81         260]
0.9
0.79
0.75
0.69
0.69
0.36
[     618.09      225.43      659.71      264.22         273]
[     565.09      212.61       606.9      246.44         271]
[     494.77       211.8      545.17      256.82         268]
[     451.92      326.22      526.88      389.24         267]
[     576.97      356.44      641.98      428.08         260]



0: 384x640 5 cars, 75.4ms
Speed: 2.0ms preprocess, 75.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)



0.91
0.79
0.76
0.71
0.62
[      615.3      231.66      660.51      273.55         273]
[     559.21      217.85      603.59      254.41         271]
[     490.55      214.09      542.55      260.94         268]
[     432.34      344.59      514.36       414.8         267]
[     562.64      379.73      631.55      454.73         260]
0.81
0.76
0.73
0.71
0.54


0: 384x640 5 cars, 76.6ms
Speed: 2.8ms preprocess, 76.6ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 cars, 71.6ms
Speed: 2.0ms preprocess, 71.6ms inference, 0.5ms postprocess per image at shape (1, 3, 384, 640)


[     611.22      241.26       660.4      285.87         273]
[     553.72      222.99      599.93      261.84         271]
[     485.78      217.56      538.97         265         268]
[      408.5      366.76      497.75       443.9         267]
[     547.56      406.31      623.07      470.56         260]
0.84
0.81
0.75
0.75
[     606.18      250.34      659.17      298.41         273]
[     547.74      230.35      594.74      270.19         271]
[     480.11      221.52      534.42      269.64         268]
[     381.74      390.08      478.99      465.36         267]



0: 384x640 5 cars, 75.1ms
Speed: 3.0ms preprocess, 75.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)



0.84
0.81
0.8
0.56
0.35
[      600.1      260.63      655.53      310.95         273]
[     540.82      238.53       589.8      280.18         271]
[     473.99       225.6      530.29      274.55         268]
0.84
0.74


0: 384x640 4 cars, 69.1ms
Speed: 2.0ms preprocess, 69.1ms inference, 0.5ms postprocess per image at shape (1, 3, 384, 640)



0.69
0.47
[     593.69      274.34      652.46      327.29         273]
[     533.12      246.11      584.06      289.59         271]
[     467.64      229.61      525.75      280.31         268]
0.87
0.71
0.7
0.46


0: 384x640 4 cars, 73.0ms
Speed: 2.0ms preprocess, 73.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)



[     628.76      256.26       664.8      297.53         274]
[     585.97      287.57      648.11      343.88         273]
[     524.92      254.36      578.94      300.52         271]
[     460.62       234.2      521.65      287.75         268]
0.75
0.75
0.71


0: 384x640 4 cars, 74.0ms
Speed: 2.0ms preprocess, 74.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)



0.65
[     625.79      264.16      665.52      308.05         274]
[     576.95      304.57      643.51      365.26         273]
[     514.67       264.3      571.29      312.53         271]
[     453.62      238.17      516.16       292.7         268]


0: 384x640 4 cars, 81.1ms
Speed: 2.0ms preprocess, 81.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 cars, 74.8ms


0.84
0.68
0.66
0.63
[     621.13      273.43       664.4      319.84         274]
[     566.73      324.76      636.92      389.85         273]
[     502.04      275.96      563.69      328.45         271]
[     445.62      243.37       510.5      299.82         268]
0.82
0.76
0.74
0.64


Speed: 2.0ms preprocess, 74.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)


[     614.17      287.11      662.37      337.77         274]
[     554.84      346.95      630.19      418.69         273]
[     490.78       287.5      555.86       343.9         271]
[     437.33      249.33      505.38      308.11         268]



0: 384x640 6 cars, 91.2ms
Speed: 5.0ms preprocess, 91.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)



0.83
0.75
0.73
0.61
0.48
0.33
[     607.36      302.94      663.95      360.57         274]
[     541.02      372.69      625.44      451.46         273]
[     475.91      301.55      546.19       362.5         271]
[     427.78      255.87      498.34      318.49         268]
0.75
0.74
0.72
0.7
0.61
0.53


0: 384x640 6 cars, 74.1ms
Speed: 2.4ms preprocess, 74.1ms inference, 2.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 cars, 72.0ms
Speed: 3.2ms preprocess, 72.0ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)


[        598      320.15      661.35      384.35         274]
[     524.84      398.02      614.53       470.8         273]
[     459.39       317.3      536.14      383.43         271]
[     417.66      263.76      491.35      329.83         268]
0.79
0.75
0.69
0.65
0.58
[     585.28      341.98      654.34      412.94         274]
[     440.62       335.6      524.36      407.23         271]
[     406.46       270.7      483.31      338.36         268]



0: 384x640 5 cars, 1 truck, 81.1ms
Speed: 2.1ms preprocess, 81.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)



0.79
0.77
0.61
0.56
0.5
0.31
[     515.86      203.55       552.1      229.98         276]
[     622.33      255.68      666.84      300.88         275]
[     572.65      365.78      646.47      444.23         274]
[     418.32       357.6      510.06      436.49         271]
[        394      276.77      474.44      347.64         268]


0: 384x640 6 cars, 1 truck, 77.1ms
Speed: 3.2ms preprocess, 77.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)



0.79
0.75
0.68
0.55
0.52
0.43
0.37
[     514.92      207.01      550.49      232.46         276]
[     618.02      266.27      665.72      312.88         275]
[     559.67      390.67      636.09      467.34         274]
[     391.48      379.36      492.18      460.86         271]
[     378.98       285.1      464.09      359.81         268]
0.73
0.67
0.66
0.66
0.44
0.35


0: 384x640 6 cars, 69.8ms
Speed: 1.0ms preprocess, 69.8ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 cars, 76.3ms
Speed: 2.8ms preprocess, 76.3ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)


[     512.59      207.84      549.87      234.74         276]
[     614.19      278.79      665.07      328.56         275]
[     550.83      419.23       631.2      479.41         274]
0.77
0.69
0.66
0.47
[     339.52      303.52      441.31      392.76         277]
[     510.61      208.43      548.81      237.11         276]
[     606.64      292.98       661.3      347.03         275]



0: 384x640 5 cars, 82.5ms
Speed: 5.1ms preprocess, 82.5ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)



0.77
0.72
0.71
0.6
0.55
[     568.69      198.17      613.06      242.24         278]
[     319.86      315.04      428.45      409.25         277]
[     506.73      208.98      547.54      240.88         276]
[     601.26      307.52      663.63      368.62         275]
0.77
0.76
0.73
0.7
0.68


0: 384x640 5 cars, 68.4ms
Speed: 3.3ms preprocess, 68.4ms inference, 2.2ms postprocess per image at shape (1, 3, 384, 640)


[     563.46      201.09      610.41      249.24         278]
[     299.43      326.52      415.83      428.23         277]
[     504.22      209.96      546.25       244.7         276]
[     593.03      326.21       662.1      393.99         275]



0: 384x640 5 cars, 75.3ms
Speed: 2.1ms preprocess, 75.3ms inference, 2.1ms postprocess per image at shape (1, 3, 384, 640)



0.86
0.8
0.79
0.68
0.63
[     560.08       204.6      609.39      255.96         278]
[     276.08       338.6      401.71      448.71         277]
[     501.88      213.05      543.93      249.29         276]
[     580.74      348.67      653.42      422.36         275]


0: 384x640 5 cars, 87.5ms
Speed: 2.5ms preprocess, 87.5ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)


0.72
0.72
0.68
0.67
0.67
[     631.58      250.22      670.47      304.12         279]
[     555.89      206.04      608.82      261.91         278]
[     249.68      353.25         383      465.83         277]
[     499.35      217.02      541.51      254.03         276]
[      568.4      375.99      641.49      454.21         275]
