In [105]:
import cv2
from ultralytics import YOLO
import cvzone
import math

from sort import *

In [106]:
# creating web cam object
# cap = cv2.VideoCapture(0)
cap = cv2.VideoCapture('./Videos/cars.mp4')
#cap.set(3,1280) # for width
#cap.set(4,720) #for height

In [107]:
model = YOLO('./Yolo-Weights/yolov8l.pt')

In [108]:
# classes that will be detected and displayed
classNames = ["person", "bicycle", "car", "motorbike", "aeroplane", "bus", "train", "truck", "boat",
              "traffic light", "fire hydrant", "stop sign", "parking meter", "bench", "bird", "cat",
              "dog", "horse", "sheep", "cow", "elephant", "bear", "zebra", "giraffe", "backpack", "umbrella",
              "handbag", "tie", "suitcase", "frisbee", "skis", "snowboard", "sports ball", "kite", "baseball bat",
              "baseball glove", "skateboard", "surfboard", "tennis racket", "bottle", "wine glass", "cup",
              "fork", "knife", "spoon", "bowl", "banana", "apple", "sandwich", "orange", "broccoli",
              "carrot", "hot dog", "pizza", "donut", "cake", "chair", "sofa", "pottedplant", "bed",
              "diningtable", "toilet", "tvmonitor", "laptop", "mouse", "remote", "keyboard", "cell phone",
              "microwave", "oven", "toaster", "sink", "refrigerator", "book", "clock", "vase", "scissors",
              "teddy bear", "hair drier", "toothbrush" , "pen"
              ]

In [109]:
mask = cv2.imread('./mask.png')

In [110]:
# creating a instance for tracking
tracker = Sort(max_age=20,min_hits=3,iou_threshold=0.3)

In [111]:
while True:
    success, img = cap.read()
    #overlay mask on the image/webcam feed
    imageRegion = cv2.bitwise_and(img,mask)
    # results = model(img,stream=True)
    results = model(imageRegion,stream=True)
    
    detections = np.empty((0,5))
    
    for r in results:
        boxes = r.boxes
        for box in boxes:
            # xy1 are points and xy2 are height and width
            x1,y1,x2,y2 = box.xyxy[0]
            # converting them into integers instead for tensor 
            x1,y1,x2,y2 = int(x1),int(y1),int(x2),int(y2)
            # cv2.rectangle(img,(x1,y1),(x2,y2),(255,0,255),3) #using cv2 reactangle
            w,h = x2-x1 , y2-y1
            bbox = int(x1),int(y1),int(w),int(h)
            
            # print(x1,y1,x2,y2)
            
            # cvzone.cornerRect(img,(x1,y1,w,h),l=9) #using cvzone rectange
            
            #confidence
            conf = math.ceil((box.conf[0]*100))/100 #for confidence values
            print(conf)
            #classnames
            cls = int(box.cls[0])
            #to display conf and object class on webcam
            currentclass = classNames[cls]
            
            if currentclass == "car" or currentclass == "truck" or currentclass == "bus" or currentclass == "motorbike" and conf>0.3 :
                cvzone.putTextRect(img,f'{currentclass} {conf}',(max(0,x1),max(35,y1)) , scale=0.6,thickness=1,offset=3)
                cvzone.cornerRect(img,(x1,y1,w,h),l=9) #using cvzone rectange
                currentArrays = np.array([x1,y1,x2,y2,conf])
                detections = np.vstack((detections,currentArrays))
            
    resultsTracker = tracker.update(detections)
    
    for result in resultsTracker:
        x1,y1,x2,y2,id = result
        print(result)
    
    cv2.imshow("Image",img)
    # cv2.imshow("ImageRegion",imageRegion)
    # cv2.waitKey(1)
    # Wait for a key event, but only for a short duration (10 milliseconds)
    # If the key is Esc (27), then break out of the loop and close the webcam
    if cv2.waitKey(1) == 27:
        break

# Release the webcam and close all OpenCV windows
cap.release()
cv2.destroyAllWindows()


0: 384x640 3 cars, 881.9ms
Speed: 31.3ms preprocess, 881.9ms inference, 22.2ms postprocess per image at shape (1, 3, 384, 640)



0.81
0.8
0.67
[        571         316         651         429           3]
[        378         348         495         457           2]
[        458         226         509         270           1]


0: 384x640 3 cars, 846.6ms
Speed: 7.0ms preprocess, 846.6ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)



0.88
0.83
0.82
[     568.92      322.12      649.08      435.88           3]
[     373.98      352.02      493.02      462.98           2]
[     456.14      227.88      506.86      271.12           1]


0: 384x640 4 cars, 703.3ms
Speed: 2.7ms preprocess, 703.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)



0.89
0.84
0.78
0.4
[        624         198         653         214           4]
[     559.26      345.51      647.22      465.01           3]
[     355.99      366.25      476.77      470.04           2]
[     449.35         234      502.12      279.29           1]


0: 384x640 5 cars, 705.1ms
Speed: 2.0ms preprocess, 705.1ms inference, 3.0ms postprocess per image at shape (1, 3, 384, 640)



0.84
0.82
0.75
0.74
0.56
[     548.26      386.26      630.01      477.31           3]
[     331.78       390.1      452.71      473.44           2]
[     438.11      241.99      494.47      290.71           1]


0: 384x640 5 cars, 713.8ms
Speed: 2.0ms preprocess, 713.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)


0.86
0.82
0.68
0.54
0.41
[     323.07      414.46         433      474.06           2]
[     427.65      251.39      486.44       302.2           1]



0: 384x640 4 cars, 789.8ms
Speed: 2.3ms preprocess, 789.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)



0.76
0.74
0.69
0.35
[     612.44      200.77      660.84      240.05           4]
[     416.82      259.33      478.98      313.22           1]


0: 384x640 3 cars, 701.0ms
Speed: 3.5ms preprocess, 701.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)



0.87
0.85
0.76
[     508.66      198.23      548.12      213.81           5]
[     610.06      205.82      662.84      251.21           4]
[     404.34      268.07      469.71      324.95           1]


0: 384x640 4 cars, 715.8ms
Speed: 2.4ms preprocess, 715.8ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)


0.85
0.82
0.76
0.5
[     503.99      198.79      547.62       217.8           5]
[     606.76      212.94      663.09       263.4           4]
[     391.16      276.93      460.74      337.04           1]



0: 384x640 4 cars, 1 motorcycle, 847.3ms
Speed: 3.1ms preprocess, 847.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)



0.85
0.8
0.76
0.3
0.29
[     499.42      199.23      545.73      221.57           5]
[        602      221.48      662.59      277.13           4]
[     376.62      287.98      450.31      351.19           1]


0: 384x640 4 cars, 724.7ms
Speed: 3.0ms preprocess, 724.7ms inference, 0.9ms postprocess per image at shape (1, 3, 384, 640)



0.88
0.79
0.76
0.41
[     495.08      199.74      543.92      225.85           5]
[     598.94      231.02       662.5      290.74           4]
[     360.39      299.94      438.56      366.59           1]


0: 384x640 4 cars, 756.9ms
Speed: 3.0ms preprocess, 756.9ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)



0.89
0.8
0.72
0.66
[     491.09      201.02      541.16      230.26           5]
[     592.07      242.59      657.35      305.97           4]
[      341.7      312.76      425.58      384.53           1]


0: 384x640 4 cars, 746.1ms
Speed: 3.2ms preprocess, 746.1ms inference, 2.5ms postprocess per image at shape (1, 3, 384, 640)



0.89
0.84
0.81
0.62
[     486.58      203.99      537.36         236           5]
[      584.9      255.12      653.48      323.48           4]
[     321.03       326.3      411.27      402.96           1]


0: 384x640 5 cars, 795.3ms
Speed: 3.5ms preprocess, 795.3ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)



0.88
0.85
0.77
0.69
0.52
[     572.43      200.38      617.21      224.49           9]
[     481.31      207.08      533.09         242           5]
[     577.31      269.18      649.77      343.25           4]
[     297.61      342.61      395.23      424.97           1]


0: 384x640 5 cars, 714.0ms
Speed: 2.0ms preprocess, 714.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)


0.86
0.83
0.78
0.74
0.5
[     568.93       202.2      614.68      230.48           9]
[     476.39      211.65      528.71      248.63           5]
[     567.95      285.23      645.78      366.34           4]
[     271.03      360.17       376.8      449.36           1]



0: 384x640 5 cars, 1 motorcycle, 703.5ms
Speed: 2.1ms preprocess, 703.5ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)



0.89
0.84
0.81
0.77
0.56
0.45
[     565.71      207.21       611.8      238.65           9]
[     470.31      216.77      523.61      256.13           5]
[     557.39      302.92      640.96      392.31           4]
[     241.31      376.35      354.89      467.17           1]


0: 384x640 1 person, 5 cars, 1 motorcycle, 723.7ms
Speed: 3.5ms preprocess, 723.7ms inference, 0.5ms postprocess per image at shape (1, 3, 384, 640)



0.88
0.86
0.83
0.78
0.61
0.51
0.27
[     629.52      199.82      658.42       243.5          10]
[     561.59      212.26       608.4      246.92           9]
[     462.69      222.11      517.35      263.23           5]
[     543.12       324.1      631.18      421.67           4]
[     209.38      393.24      330.83      476.59           1]


0: 384x640 5 cars, 1 motorcycle, 687.5ms
Speed: 5.1ms preprocess, 687.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)



0.84
0.84
0.81
0.75
0.7
0.42
[     626.13      200.12      660.78      254.16          10]
[     556.88      219.29      603.75      256.66           9]
[     454.88      227.85      510.99      270.49           5]
[     527.12      347.34      622.58      454.09           4]
[     179.67      414.72      308.29      481.82           1]


0: 384x640 5 cars, 1 motorcycle, 696.5ms
Speed: 5.2ms preprocess, 696.5ms inference, 8.0ms postprocess per image at shape (1, 3, 384, 640)



0.89
0.82
0.77
0.74
0.62
0.52
[     528.07      266.61      552.32      320.38          11]
[     622.41      201.54      662.03      264.57          10]
[     551.28      226.16       599.4      266.34           9]
[     446.41      234.28      504.55      279.23           5]
[     510.64       370.1      615.66      472.96           4]


0: 384x640 5 cars, 1 motorcycle, 706.7ms
Speed: 4.2ms preprocess, 706.7ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)



0.79
0.79
0.78
0.68
0.64
0.55
[     518.32      278.72       543.5       334.7          11]
[     617.41      207.95      661.98       278.8          10]
[     545.71      233.71       595.5      276.55           9]
[     436.37       241.8      496.78      288.98           5]
[     496.84      396.73      608.54       482.6           4]


0: 384x640 1 person, 4 cars, 1 motorcycle, 1 truck, 758.3ms
Speed: 2.0ms preprocess, 758.3ms inference, 2.3ms postprocess per image at shape (1, 3, 384, 640)



0.86
0.83
0.72
0.67
0.59
0.55
0.35
[     508.83      305.02       532.5      355.31          11]
[      611.6      216.52      661.92      294.37          10]
[     538.83      242.51      591.11      288.58           9]
[      425.1      250.68      487.87      299.44           5]


0: 384x640 1 person, 4 cars, 1 motorcycle, 718.1ms
Speed: 2.7ms preprocess, 718.1ms inference, 8.1ms postprocess per image at shape (1, 3, 384, 640)



0.87
0.85
0.74
0.66
0.61
0.53
[     549.59      199.08      594.15       227.2          12]
[      496.9      323.89      521.99      375.09          11]
[     605.95      227.53      660.78      310.65          10]
[     531.66      251.93      585.71      300.42           9]
[      412.1      259.74      477.86      311.12           5]


0: 384x640 1 person, 3 cars, 1 motorcycle, 1 truck, 691.2ms
Speed: 3.0ms preprocess, 691.2ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)



0.83
0.82
0.8
0.56
0.53
0.52
[     545.51      200.27      593.21      233.19          12]
[     482.33      344.05      510.03      398.34          11]
[      600.7      240.16       660.3      329.71          10]
[     523.39      262.01      580.94      313.69           9]
[      397.3      270.27      466.66      324.46           5]


0: 384x640 1 person, 3 cars, 1 motorcycle, 1 truck, 700.8ms
Speed: 2.5ms preprocess, 700.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)



0.86
0.83
0.8
0.68
0.66
0.53
[     541.42      202.85       591.6      239.22          12]
[     465.19      370.08      495.19      426.18          11]
[     593.39      253.61      660.27      351.44          10]
[     513.79      274.35      574.71      329.42           9]
[     380.58      282.13      454.32      339.56           5]


0: 384x640 1 person, 3 cars, 2 motorcycles, 1 truck, 710.1ms
Speed: 3.0ms preprocess, 710.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)


0.86
0.83
0.81
0.67
0.45
0.35
0.29
[     536.56      207.55      589.11       247.8          12]
[      445.4      398.89      478.43      458.21          11]
[     583.63      269.37      659.45       376.7          10]
[     502.21      287.07      567.46      346.47           9]
[     360.93       295.2      440.53      356.55           5]
