In [85]:
import cv2
from ultralytics import YOLO
import cvzone
import math

from sort import *

In [86]:
# creating web cam object
# cap = cv2.VideoCapture(0)
cap = cv2.VideoCapture('./Videos/cars.mp4')
#cap.set(3,1280) # for width
#cap.set(4,720) #for height

In [87]:
model = YOLO('./Yolo-Weights/yolov8n.pt')

In [88]:
# classes that will be detected and displayed
classNames = ["person", "bicycle", "car", "motorbike", "aeroplane", "bus", "train", "truck", "boat",
              "traffic light", "fire hydrant", "stop sign", "parking meter", "bench", "bird", "cat",
              "dog", "horse", "sheep", "cow", "elephant", "bear", "zebra", "giraffe", "backpack", "umbrella",
              "handbag", "tie", "suitcase", "frisbee", "skis", "snowboard", "sports ball", "kite", "baseball bat",
              "baseball glove", "skateboard", "surfboard", "tennis racket", "bottle", "wine glass", "cup",
              "fork", "knife", "spoon", "bowl", "banana", "apple", "sandwich", "orange", "broccoli",
              "carrot", "hot dog", "pizza", "donut", "cake", "chair", "sofa", "pottedplant", "bed",
              "diningtable", "toilet", "tvmonitor", "laptop", "mouse", "remote", "keyboard", "cell phone",
              "microwave", "oven", "toaster", "sink", "refrigerator", "book", "clock", "vase", "scissors",
              "teddy bear", "hair drier", "toothbrush" , "pen"
              ]

In [89]:
mask = cv2.imread('./mask.png')

In [90]:
# creating a instance for tracking
tracker = Sort(max_age=20,min_hits=3,iou_threshold=0.3)

# we will make a line and count after that 
limits = [400,297,673,297]
totalcounts=0

In [91]:
while True:
    success, img = cap.read()
    #overlay mask on the image/webcam feed
    imageRegion = cv2.bitwise_and(img,mask)
    # results = model(img,stream=True)
    results = model(imageRegion,stream=True)
    
    detections = np.empty((0,5))
    
    for r in results:
        boxes = r.boxes
        for box in boxes:
            # xy1 are points and xy2 are height and width
            x1,y1,x2,y2 = box.xyxy[0]
            # converting them into integers instead for tensor 
            x1,y1,x2,y2 = int(x1),int(y1),int(x2),int(y2)
            # cv2.rectangle(img,(x1,y1),(x2,y2),(255,0,255),3) #using cv2 reactangle
            w,h = x2-x1 , y2-y1
            bbox = int(x1),int(y1),int(w),int(h)
            
            # print(x1,y1,x2,y2)
            
            # cvzone.cornerRect(img,(x1,y1,w,h),l=9) #using cvzone rectange
            
            #confidence
            conf = math.ceil((box.conf[0]*100))/100 #for confidence values
            print(conf)
            #classnames
            cls = int(box.cls[0])
            #to display conf and object class on webcam
            currentclass = classNames[cls]
            
            if currentclass == "car" or currentclass == "truck" or currentclass == "bus" or currentclass == "motorbike" and conf>0.3 :
                # cvzone.putTextRect(img,f'{currentclass} {conf}',(max(0,x1),max(35,y1)) , scale=0.6,thickness=1,offset=3)
                # cvzone.cornerRect(img,(x1,y1,w,h),l=9 , rt=5) #using cvzone rectange
                currentArrays = np.array([x1,y1,x2,y2,conf])
                detections = np.vstack((detections,currentArrays))
            
    resultsTracker = tracker.update(detections)
    
    cv2.line(img,(limits[0],limits[1]),(limits[2],limits[3]),(0,0,255),5)
    
    for result in resultsTracker:
        x1,y1,x2,y2,id = result
        # converting them into integers instead for tensor 
        x1,y1,x2,y2 = int(x1),int(y1),int(x2),int(y2)
        print(result)
        w,h = x2-x1 , y2-y1
        cvzone.cornerRect(img,(x1,y1,w,h),l=9 , rt=2,colorR=(255,0,0))
        # cvzone.putTextRect(img,f' {int(id)}',(max(0,x1),max(35,y1)) , scale=2,thickness=3,offset=10)
        
        cx , cy = x1+w//2,y1+h//2
        cv2.circle(img,(cx,cy),5,(255,0,255),cv2.FILLED)
        
        if limits[0] <cx< limits[2] and limits[1]-20<cy<limits[1]+20:
            totalcounts += 1
            cvzone.putTextRect(img,f' {int(totalcounts)}',(max(0,x1),max(35,y1)) , scale=2,thickness=3,offset=10)
        
    cvzone.putTextRect(img,f'Count : {totalcounts}',(90,90)) 
    
    cv2.imshow("Image",img)
    # cv2.imshow("ImageRegion",imageRegion)
    # cv2.waitKey(1)
    # Wait for a key event, but only for a short duration (10 milliseconds)
    # If the key is Esc (27), then break out of the loop and close the webcam
    if cv2.waitKey(0) == 27:
        break

# Release the webcam and close all OpenCV windows
cap.release()
cv2.destroyAllWindows()


0: 384x640 4 cars, 162.5ms
Speed: 8.0ms preprocess, 162.5ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)


0.82
0.79
0.49
0.39
[        572         322         651         429         331]
[        573         364         626         429         330]
[        378         348         497         457         329]
[        456         225         510         270         328]



0: 384x640 4 cars, 100.0ms
Speed: 2.9ms preprocess, 100.0ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)


0.8
0.77
0.53
0.52
[     568.48      320.73      651.52      436.27         331]
[     572.26      371.69      627.74      438.31         330]
[     373.12      349.89      492.88      459.11         329]
[     454.74      228.22      508.26      273.78         328]



0: 384x640 2 cars, 152.8ms
Speed: 7.0ms preprocess, 152.8ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 cars, 80.9ms
Speed: 0.0ms preprocess, 80.9ms inference, 3.0ms postprocess per image at shape (1, 3, 384, 640)


0.84
0.8
[     355.68      365.44      476.85      468.27         329]
[     447.68      233.63      501.97      279.13         328]
0.53
0.53
0.38
[     340.18      389.65      456.14      471.21         329]
[     437.23      243.33      494.88       291.5         328]



0: 384x640 2 cars, 81.4ms
Speed: 8.0ms preprocess, 81.4ms inference, 7.5ms postprocess per image at shape (1, 3, 384, 640)


0.62
0.33
[     329.19      415.66      431.62      473.23         329]
[     425.72       251.9      488.28      303.79         328]



0: 384x640 2 cars, 86.6ms
Speed: 0.0ms preprocess, 86.6ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)



0.81
0.64
[     414.95      260.16      478.66      313.73         328]


0: 384x640 3 cars, 87.7ms
Speed: 0.0ms preprocess, 87.7ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)


0.85
0.66
0.38
[     403.36       268.9      470.65       325.2         328]



0: 384x640 3 cars, 106.7ms
Speed: 1.1ms preprocess, 106.7ms inference, 4.5ms postprocess per image at shape (1, 3, 384, 640)



0.81
0.78
0.4
[     391.16      277.99      461.47      336.97         328]


0: 384x640 3 cars, 81.6ms
Speed: 0.0ms preprocess, 81.6ms inference, 8.0ms postprocess per image at shape (1, 3, 384, 640)


0.87
0.83
0.65
[     604.53      221.37      660.48      279.16         332]
[      375.2      287.28      450.66      351.49         328]



0: 384x640 3 cars, 116.1ms
Speed: 3.0ms preprocess, 116.1ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)


0.9
0.82
0.68
[     494.81      198.91      541.78      227.66         333]
[     600.32      231.93      660.04      293.02         332]
[     359.19      299.31       439.4      367.66         328]



0: 384x640 4 cars, 88.3ms
Speed: 0.0ms preprocess, 88.3ms inference, 8.0ms postprocess per image at shape (1, 3, 384, 640)


0.87
0.85
0.68
0.32
[     489.11      199.67      538.32      232.06         333]
[     592.72      243.59      655.27      308.58         332]
[     340.76      311.86      427.07      385.53         328]



0: 384x640 3 cars, 96.2ms
Speed: 0.0ms preprocess, 96.2ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)


0.85
0.63
0.56
[     484.86      203.33      535.69      238.66         333]
[     585.29      254.56      653.08      325.61         332]
[     320.84      325.91      412.35      403.99         328]



0: 384x640 4 cars, 96.9ms
Speed: 5.4ms preprocess, 96.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)



0.87
0.82
0.71
0.45
[     480.47      205.39      531.74      243.35         333]
[     578.04      268.94      652.39      346.41         332]
[     296.59      342.28      394.62      425.48         328]


0: 384x640 4 cars, 83.0ms
Speed: 1.0ms preprocess, 83.0ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)



0.86
0.77
0.75
0.6
[     475.45      209.69      527.24      249.49         333]
[     570.86       284.7      654.98      370.28         332]
[     270.79      358.68      375.77      448.23         328]


0: 384x640 4 cars, 93.2ms
Speed: 3.2ms preprocess, 93.2ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)


0.76
0.75
0.71
0.54
[     569.45      205.93      608.21      237.79         334]
[     468.96      216.06      521.76      256.86         333]
[     556.32      302.74      643.06      394.69         332]
[     237.52       376.3      352.94       467.5         328]



0: 384x640 6 cars, 92.1ms
Speed: 1.6ms preprocess, 92.1ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 cars, 79.3ms


0.81
0.77
0.57
0.48
0.33
0.27
[     566.59      213.18      604.94      245.77         334]
[     462.11      222.16      516.46      264.96         333]
[     541.03      324.57      632.09      424.97         332]
[     199.79       392.6      327.73      477.97         328]
0.76
0.75
0.72
0.68
0.36


Speed: 1.2ms preprocess, 79.3ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)


[     560.37      220.51      600.68       255.4         334]
[     453.93      228.74      508.43      272.69         333]
[     526.23      347.52       623.5      456.22         332]



0: 384x640 4 cars, 91.9ms
Speed: 5.5ms preprocess, 91.9ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)


0.81
0.73
0.7
0.64
[     554.43      227.52      596.94      265.75         334]
[     445.59      234.36      503.11      281.37         333]
[     510.66      370.03      612.19      473.24         332]



0: 384x640 5 cars, 1 truck, 95.0ms
Speed: 3.8ms preprocess, 95.0ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)



0.88
0.76
0.72
0.59
0.47
0.29
[     616.58      206.36      659.81       278.2         336]
[     548.11      234.61       593.2      275.37         334]
[     435.36      241.14      495.33      290.19         333]
[     495.38      396.39      600.68      482.21         332]


0: 384x640 1 person, 5 cars, 85.7ms
Speed: 1.7ms preprocess, 85.7ms inference, 0.5ms postprocess per image at shape (1, 3, 384, 640)


0.87
0.85
0.69
0.47
0.45
0.33
[     612.81      221.12      660.92       294.3         336]
[     540.47      242.77      588.66      287.05         334]
[     424.74      248.97      487.68       300.4         333]



0: 384x640 4 cars, 94.1ms
Speed: 1.1ms preprocess, 94.1ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)


0.85
0.83
0.67
0.66
[     606.76      230.36       660.4      310.78         336]
[     532.97      252.22      583.91      299.85         334]
[     411.73      258.64      477.74      312.96         333]



0: 384x640 4 cars, 96.0ms
Speed: 4.0ms preprocess, 96.0ms inference, 3.0ms postprocess per image at shape (1, 3, 384, 640)



0.86
0.86
0.73
0.73
[     545.29      201.49      594.04       233.8         338]
[     598.61      241.14      657.95         329         336]
[     524.13      262.52       578.5      313.29         334]
[     396.97      268.35      466.52      325.03         333]


0: 384x640 1 person, 4 cars, 87.2ms
Speed: 9.6ms preprocess, 87.2ms inference, 3.1ms postprocess per image at shape (1, 3, 384, 640)


0.8
0.74
0.65
0.52
0.29
[     541.45      206.36      590.84      240.14         338]
[     591.61      253.86      657.97      350.48         336]
[     514.42      273.06      572.59      327.66         334]
[     379.68      281.12       454.1      341.72         333]



0: 384x640 1 person, 4 cars, 95.3ms
Speed: 3.2ms preprocess, 95.3ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)



0.88
0.84
0.83
0.61
0.34
[     535.79         209      587.96      248.04         338]
[     581.64      270.52       656.1      376.57         336]
[     503.23      286.86       565.7      345.78         334]
[     360.42      294.23      440.98      358.95         333]


0: 384x640 5 cars, 88.8ms
Speed: 1.5ms preprocess, 88.8ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)


0.85
0.83
0.82
0.44
0.31
[     531.63      213.02      584.59         255         338]
[     571.06      289.41      653.13      406.06         336]
[     490.71      302.15      557.93       366.3         334]
[     338.28      308.86      425.22      378.87         333]



0: 384x640 5 cars, 81.6ms
Speed: 7.1ms preprocess, 81.6ms inference, 8.3ms postprocess per image at shape (1, 3, 384, 640)


0.86
0.82
0.75
0.47
0.27
[     526.61      219.11      581.04      264.21         338]
[     555.27      313.97      642.69      442.52         336]
[     476.89      318.34      548.69      387.95         334]
[     311.87      326.94       407.1      402.12         333]



0: 384x640 4 cars, 96.2ms
Speed: 8.0ms preprocess, 96.2ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)



0.83
0.82
0.72
0.58
[     520.08      227.07      575.89      273.66         338]
[      538.8      334.25      632.38      465.67         336]
[     458.92      337.32         538      413.42         334]
[     281.08      347.26       385.7      428.89         333]


0: 384x640 4 cars, 82.5ms
Speed: 2.4ms preprocess, 82.5ms inference, 5.5ms postprocess per image at shape (1, 3, 384, 640)



0.8
0.73
0.5
0.46
[     513.82      234.47      571.44      283.68         338]
[     439.82      359.87      525.06      442.99         334]
[     247.07      368.52      360.79      455.52         333]


0: 384x640 4 cars, 84.8ms
Speed: 6.5ms preprocess, 84.8ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)



0.88
0.77
0.48
0.38
[      506.7      243.09      566.19      293.79         338]
[     418.06      381.22      510.31      464.08         334]
[      203.6      391.22      329.81      472.39         333]


0: 384x640 3 cars, 81.3ms
Speed: 6.0ms preprocess, 81.3ms inference, 8.0ms postprocess per image at shape (1, 3, 384, 640)


0.84
0.52
0.5
[     493.27      205.24      535.09      237.64         340]
[     497.78      252.34      560.17      306.36         338]
[     396.41      404.98      495.78      476.39         334]



0: 384x640 2 cars, 99.7ms
Speed: 5.9ms preprocess, 99.7ms inference, 10.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 cars, 82.7ms


0.86
0.75
[     487.24      210.07      530.31      244.65         340]
[     488.99      261.15      554.43      317.82         338]
0.9
0.8


Speed: 3.5ms preprocess, 82.7ms inference, 3.0ms postprocess per image at shape (1, 3, 384, 640)


[      479.5      214.97      524.83      251.89         340]
[     478.81       271.1      548.27      332.15         338]



0: 384x640 2 cars, 91.8ms
Speed: 0.0ms preprocess, 91.8ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)



0.87
0.8
[     471.22      222.01      517.76      260.56         340]
[     466.73      283.64      540.06      348.66         338]


0: 384x640 2 cars, 87.8ms
Speed: 4.0ms preprocess, 87.8ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 cars, 82.1ms


0.9
0.78
[     462.39      230.16      511.27      269.97         340]
[      451.9      297.82      531.17      369.22         338]
0.9
0.86


Speed: 5.0ms preprocess, 82.1ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)



[     452.11      237.56      504.24      280.02         340]
[     436.87      311.74       521.9      388.83         338]


0: 384x640 2 cars, 86.9ms
Speed: 7.0ms preprocess, 86.9ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)


0.9
0.84
[      440.9      245.43      495.44      290.18         340]
[     419.02      329.63      510.02      413.13         338]



0: 384x640 2 cars, 96.5ms
Speed: 0.0ms preprocess, 96.5ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)


0.88
0.83
[     430.16      254.05      487.92      301.11         340]
[      398.3       350.6      497.05      442.15         338]



0: 384x640 3 cars, 95.3ms
Speed: 3.2ms preprocess, 95.3ms inference, 4.0ms postprocess per image at shape (1, 3, 384, 640)


0.84
0.83
0.41
[     415.99      264.31      477.17      313.59         340]
[     375.16      368.57      481.12      461.96         338]



0: 384x640 3 cars, 96.2ms
Speed: 8.0ms preprocess, 96.2ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)


0.85
0.79
0.56
[     399.67      275.37      464.82       328.4         340]
[     352.74      388.74      464.47      474.22         338]



0: 384x640 3 cars, 104.3ms
Speed: 6.0ms preprocess, 104.3ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)


0.83
0.73
0.35
[     382.19       286.5      452.29      342.27         340]
[      330.7      406.11      444.89      480.02         338]



0: 384x640 2 cars, 107.4ms
Speed: 4.7ms preprocess, 107.4ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 cars, 85.3ms
Speed: 5.3ms preprocess, 85.3ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)


0.82
0.69
[     614.63      213.65      655.24      258.92         341]
[     361.79      301.34      437.62      360.64         340]
0.8
0.78
0.33
[     611.21      223.17      656.82      273.28         341]
[     339.65      316.37      420.88      379.88         340]



0: 384x640 2 cars, 89.7ms
Speed: 6.5ms preprocess, 89.7ms inference, 4.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 cars, 83.1ms


0.77
0.77
[     606.18      232.37      654.72      285.46         341]
[     313.72      333.46      402.64      402.64         340]
0.87
0.85
0.28


Speed: 8.0ms preprocess, 83.1ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 cars, 82.4ms
Speed: 5.5ms preprocess, 82.4ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)


[     601.67      241.12      655.52      299.39         341]
[     283.29      354.83      379.73      429.74         340]
0.82
0.64
0.27


[      594.2      253.53      650.69      316.33         341]
[     249.65      376.96      354.72      456.61         340]


0: 384x640 3 cars, 110.9ms
Speed: 2.0ms preprocess, 110.9ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)


0.79
0.62
0.26
[     504.86      199.96      541.54      225.99         342]
[     588.86      266.29      649.04      333.77         341]
[     203.45      399.86      321.36      473.66         340]



0: 384x640 2 cars, 91.6ms
Speed: 4.3ms preprocess, 91.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)


0.72
0.65
[      502.1      200.12      540.13      228.37         342]
[     580.02      282.18      645.38      356.43         341]



0: 384x640 3 cars, 99.5ms
Speed: 5.3ms preprocess, 99.5ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)


0.68
0.66
0.3
[     499.94      200.68      538.94      230.62         342]
[     570.05      300.97      638.87      381.82         341]



0: 384x640 3 cars, 93.4ms
Speed: 3.3ms preprocess, 93.4ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 cars, 84.8ms
Speed: 3.5ms preprocess, 84.8ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)


0.77
0.56
0.55
[     497.62      202.03      537.46       234.3         342]
[     559.57      322.97      631.47      411.28         341]
0.7
0.6
0.58
[     496.08      202.65      536.44      237.37         342]
[     546.04      347.37      625.33      445.57         341]



0: 384x640 3 cars, 80.9ms
Speed: 0.0ms preprocess, 80.9ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 cars, 81.6ms
Speed: 0.0ms preprocess, 81.6ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)


0.42
0.4
0.35
[     617.17      215.28      657.72      263.98         343]
[     494.32      205.15      534.71       241.5         342]
[     534.14      371.47      616.29      468.11         341]
0.72
0.7
[     615.48      225.38      659.18      274.16         343]
[      491.4      209.23      531.76      245.78         342]



0: 384x640 2 cars, 96.6ms
Speed: 8.0ms preprocess, 96.6ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 cars, 81.2ms
Speed: 0.0ms preprocess, 81.2ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)


0.77
0.7
[     611.06      232.89      659.15      285.45         343]
[     488.36      211.66      528.74      248.94         342]
0.84
0.59
[     606.84      240.38      659.81      297.69         343]
[     485.52      215.69      526.15      253.47         342]



0: 384x640 4 cars, 93.2ms
Speed: 3.1ms preprocess, 93.2ms inference, 2.5ms postprocess per image at shape (1, 3, 384, 640)


0.73
0.72
0.38
0.34
[     601.38      249.53      657.14      309.97         343]
[     481.88       219.8      523.93      258.36         342]



0: 384x640 5 cars, 106.1ms
Speed: 6.6ms preprocess, 106.1ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)


0.82
0.77
0.57
0.55
0.47
[     593.56      261.51      652.55      325.44         343]
[     478.21      223.33      520.93      262.63         342]



0: 384x640 5 cars, 90.8ms
Speed: 4.1ms preprocess, 90.8ms inference, 6.0ms postprocess per image at shape (1, 3, 384, 640)


0.83
0.79
0.74
0.5
0.33
[     587.31      274.12      651.06      343.05         343]
[     473.71      228.02      518.46      268.59         342]



0: 384x640 5 cars, 96.4ms
Speed: 8.3ms preprocess, 96.4ms inference, 8.0ms postprocess per image at shape (1, 3, 384, 640)


0.84
0.82
0.77
0.74
0.41
[     562.87      202.38      609.62      239.81         345]
[     620.22      225.22      661.41      273.62         344]
[     579.05      287.69      649.27      363.32         343]
[     469.01      232.65      514.78      273.68         342]



0: 384x640 5 cars, 90.0ms
Speed: 1.0ms preprocess, 90.0ms inference, 8.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 cars, 90.6ms


0.85
0.77
0.75
0.73
0.45
[     557.65      206.61      606.72      247.91         345]
[     615.98      234.08      662.27      287.78         344]
[     569.63      304.16      642.47      385.27         343]
[     463.55       238.5      510.68      280.47         342]
0.85
0.75
0.74
0.63
0.61


Speed: 0.0ms preprocess, 90.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)



[      502.9      200.29       542.9      223.14         347]
[     551.91      212.92      602.89      257.61         345]
[     610.97      238.17       663.4      299.62         344]
[     558.73      322.33      635.59      411.13         343]
[     457.03       243.3      505.89      287.43         342]


0: 384x640 6 cars, 85.6ms
Speed: 2.8ms preprocess, 85.6ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)


0.88
0.76
0.7
0.65
0.63
0.42
[     501.94      200.74      543.87      226.32         347]
[     545.62      220.86      598.49      268.11         345]
[      607.9      244.82      663.89      310.27         344]
[        545      344.38      628.36      441.72         343]
[     451.24      247.69      502.36      293.13         342]
